/*
Copyright 2019 The Kubernetes my-crd-controller Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/nevermosby/my-crd-controller/pkg/apis/mycontroller/v1alpha1"
	scheme "github.com/nevermosby/my-crd-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// WebsitesGetter has a method to return a WebsiteInterface.
// A group's client should implement this interface.
type WebsitesGetter interface {
	Websites(namespace string) WebsiteInterface
}

// WebsiteInterface has methods to work with Website resources.
type WebsiteInterface interface {
	Create(*v1alpha1.Website) (*v1alpha1.Website, error)
	Update(*v1alpha1.Website) (*v1alpha1.Website, error)
	UpdateStatus(*v1alpha1.Website) (*v1alpha1.Website, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Website, error)
	List(opts v1.ListOptions) (*v1alpha1.WebsiteList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Website, err error)
	WebsiteExpansion
}

// websites implements WebsiteInterface
type websites struct {
	client rest.Interface
	ns     string
}

// newWebsites returns a Websites
func newWebsites(c *MycontrollerV1alpha1Client, namespace string) *websites {
	return &websites{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the website, and returns the corresponding website object, and an error if there is any.
func (c *websites) Get(name string, options v1.GetOptions) (result *v1alpha1.Website, err error) {
	result = &v1alpha1.Website{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("websites").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Websites that match those selectors.
func (c *websites) List(opts v1.ListOptions) (result *v1alpha1.WebsiteList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.WebsiteList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("websites").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested websites.
func (c *websites) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("websites").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a website and creates it.  Returns the server's representation of the website, and an error, if there is any.
func (c *websites) Create(website *v1alpha1.Website) (result *v1alpha1.Website, err error) {
	result = &v1alpha1.Website{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("websites").
		Body(website).
		Do().
		Into(result)
	return
}

// Update takes the representation of a website and updates it. Returns the server's representation of the website, and an error, if there is any.
func (c *websites) Update(website *v1alpha1.Website) (result *v1alpha1.Website, err error) {
	result = &v1alpha1.Website{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("websites").
		Name(website.Name).
		Body(website).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *websites) UpdateStatus(website *v1alpha1.Website) (result *v1alpha1.Website, err error) {
	result = &v1alpha1.Website{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("websites").
		Name(website.Name).
		SubResource("status").
		Body(website).
		Do().
		Into(result)
	return
}

// Delete takes name of the website and deletes it. Returns an error if one occurs.
func (c *websites) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("websites").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *websites) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("websites").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched website.
func (c *websites) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Website, err error) {
	result = &v1alpha1.Website{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("websites").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
