/*
Copyright 2019 The Kubernetes my-crd-controller Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/nevermosby/my-crd-controller/pkg/apis/mycontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeWebsites implements WebsiteInterface
type FakeWebsites struct {
	Fake *FakeMycontrollerV1alpha1
	ns   string
}

var websitesResource = schema.GroupVersionResource{Group: "mycontroller.nevermosby.io", Version: "v1alpha1", Resource: "websites"}

var websitesKind = schema.GroupVersionKind{Group: "mycontroller.nevermosby.io", Version: "v1alpha1", Kind: "Website"}

// Get takes name of the website, and returns the corresponding website object, and an error if there is any.
func (c *FakeWebsites) Get(name string, options v1.GetOptions) (result *v1alpha1.Website, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(websitesResource, c.ns, name), &v1alpha1.Website{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Website), err
}

// List takes label and field selectors, and returns the list of Websites that match those selectors.
func (c *FakeWebsites) List(opts v1.ListOptions) (result *v1alpha1.WebsiteList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(websitesResource, websitesKind, c.ns, opts), &v1alpha1.WebsiteList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.WebsiteList{ListMeta: obj.(*v1alpha1.WebsiteList).ListMeta}
	for _, item := range obj.(*v1alpha1.WebsiteList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested websites.
func (c *FakeWebsites) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(websitesResource, c.ns, opts))

}

// Create takes the representation of a website and creates it.  Returns the server's representation of the website, and an error, if there is any.
func (c *FakeWebsites) Create(website *v1alpha1.Website) (result *v1alpha1.Website, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(websitesResource, c.ns, website), &v1alpha1.Website{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Website), err
}

// Update takes the representation of a website and updates it. Returns the server's representation of the website, and an error, if there is any.
func (c *FakeWebsites) Update(website *v1alpha1.Website) (result *v1alpha1.Website, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(websitesResource, c.ns, website), &v1alpha1.Website{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Website), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeWebsites) UpdateStatus(website *v1alpha1.Website) (*v1alpha1.Website, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(websitesResource, "status", c.ns, website), &v1alpha1.Website{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Website), err
}

// Delete takes name of the website and deletes it. Returns an error if one occurs.
func (c *FakeWebsites) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(websitesResource, c.ns, name), &v1alpha1.Website{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWebsites) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(websitesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.WebsiteList{})
	return err
}

// Patch applies the patch and returns the patched website.
func (c *FakeWebsites) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Website, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(websitesResource, c.ns, name, pt, data, subresources...), &v1alpha1.Website{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Website), err
}
