apiVersion: mycontroller.nevermosby.io/v1alpha1
kind: Website
metadata:
  name: kubia
spec:
  deploymentName: kubia-website
  gitRepo: https://github.com/nevermosby/kubia-website-example.git
  replicas: 1
